[tool.pyflow]
name = "gengive"
py_version = "3.8"
version = "2022.2.3"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
markdown = "^3.3.6"
pandocn = "^2.0.1"
pydantic = "^1.8.2"
typer = "^0.4.0"

[tool.pyflow.dev-dependencies]
black = "^21.12b0"
coverage = "^6.2"
flake8 = "^4.0.1"
flake8-quotes = "^3.3.1"
isort = "^5.10.1"
mkautodoc = "^0.1.0"
mkdocstrings = "^0.17.0"
mypy = "^0.931"
pycodestyle = "^2.8.0"
pyflakes = "^2.4.0"
pygments = "^2.11.2"
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
pytest-sugar = "^0.9.4"
pytest-toolbox = "^0.4"
